# Generated by Django 4.2.7 on 2025-10-21 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('interested_course', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'PhD')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('street', models.TextField()),
                ('test_type', models.CharField(max_length=10)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reading_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('listening_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('writing_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('speaking_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('attended_date', models.DateField()),
                ('document', models.FileField(max_length=500, upload_to='applicant_documents/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('Intermediate', 'Intermediate'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=20)),
                ('degree_title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('passed_year', models.CharField(max_length=4)),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('obtained_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
                'db_table': 'academics',
                'ordering': ['degree_level', '-passed_year'],
            },
        ),
    ]
